// Code generated by MockGen. DO NOT EDIT.
// Source: gateway/thailand/thailand.go

// Package mock_thailand is a generated GoMock package.
package thailand

import (
	context "context"
	entity "my_go/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// GetCBRRates mocks base method.
func (m *MockGateway) GetCBRRates(ctx context.Context) (*entity.ExchangeRates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCBRRates", ctx)
	ret0, _ := ret[0].(*entity.ExchangeRates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCBRRates indicates an expected call of GetCBRRates.
func (mr *MockGatewayMockRecorder) GetCBRRates(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCBRRates", reflect.TypeOf((*MockGateway)(nil).GetCBRRates), ctx)
}
